weights: ./runs/train/kpts-s-640/weights/last.pt
cfg: ''
data: data/projects/coco-kpts.yaml
hyp: data/hyps/x.yaml
epochs: 200
batch_size: -1
imgsz: 640
rect: false
resume: true
nosave: false
noval: false
noplots: false
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: kpts-s-640
exist_ok: false
quad: false
cos_lr: false
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
seed: 0
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/kpts-s-640
